_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "./checkpoints/mask_rcnn_r101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "output/mask_rcnn_r101/"