_BASE_: Base-BMask-R-CNN-FPN.yaml
MODEL:
  WEIGHTS: "bmask_rcnn_r101_1x.pth"
  MASK_ON: true
  RESNETS:
    DEPTH: 101
INPUT:
  MIN_SIZE_TRAIN: (800,)
TEST:
  EVAL_PERIOD: 10000
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val","lvis_v0.5_val_cocofied")
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
OUTPUT_DIR: "bmask_rcnn_r101_1x"