_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "./checkpoints/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 1203
    SCORE_THRESH_TEST: 0.0001
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("lvis_v1_train",)
  TEST: ("lvis_v1_val",)
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
SOLVER:
#  STEPS: (120000, 160000)
#  MAX_ITER: 180000  # 180000 * 16 / 100000 ~ 28.8 epochs
  WARMUP_ITERS: 500
  STEPS: (50000, 68750)  # keep same as mmdet 1x. (8, 11, 12).  100000 images per Epoch
  MAX_ITER: 75000
  CHECKPOINT_PERIOD: 75000
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001
OUTPUT_DIR: "output/lvis_v1_mask_rcnn/"

