MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 50
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "PatchDCTROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 80
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MaskRCNNPatchDCTHead"
    NUM_CONV: 4
    CLS_AGNOSTIC_MASK: False
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    POOLER_RESOLUTION: 14
    FINE_FEATURES: ["p2"]
    FINE_FEATURES_RESOLUTION: 42
    MASK_SIZE: 112
    DCT_VECTOR_DIM: 300
    MASK_SIZE_ASSEMBLE: 112
    PATCH_SIZE: 8
    PATCH_DCT_VECTOR_DIM: 6
    MASK_LOSS_PARA: 1.0
    HIDDEN_FEATURES: 1024
    PATCH_THRESHOLD: 0.30
    NUM_STAGE: 3 # include DCT stage, should be PatchDCT N_Stage+1
    MASK_LOSS_PARA_EACH_STAGE: [0.5, 0.5, 0.8]
    EVAL_GT: False # Only set to be "True" for upper bound evaluation
    DCT_LOSS_TYPE: "l1"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val","lvis_v0.5_val_cocofied")
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000,80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 90000
INPUT:
  MASK_FORMAT: "polygon"
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
OUTPUT_DIR: "output/patchdct_r50_1x_2stage/"
